### ISSUE TITLE
How does this differ from deployer-extended-wordpress?

### ISSUE THREAD

**Issue by thinkstylestudio** [sourcebroker/deployer-extended-wordpress-composer#1]
I'm looking into using one of these but I'm trying to figure out which might be the right choice. I noticed in `deployer-extended-wordpress` that you have composer.json in the root file structure example. 

I guess what I'm trying to ask is when do I want to use this one over `deployer-extended-wordpress`?

**Comment by kszymukowicz** [comment]
In "deployer-extended-wordpress" the WordPress and third party plugins are installed manually. What you have in git is basically only your theme. The good thing is that in such case you can update WordPress and plugins automatically. IMO this is preferable for low budget WordPress websites. 

In "deployer-extended-wordpress-composer" the WordPress and third party plugins are installed using composer. This way you gain more control over what is installed but at the same time to install new WordPress or new plugin version you need first to modify composer.json or do composer update (depending how big upgrade you do). Then you need to commit composer.json / composer.lock and do deploy which will install new version of WordPress and plugins. This is additional work that can not be easily automated. One of advantages of this solution is that you can easily cleanup infected WordPress/plugins files as with each deployment all php files are fresh (part from your git and part from composer repositories).
